'use server';

/**
 * @fileOverview A patient report generation AI agent.
 *
 * - generatePatientReport - A function that handles the patient report generation process.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import type { GeneratePatientReportInput, GeneratePatientReportOutput } from '@/ai/types';
import { GeneratePatientReportInputSchema, GeneratePatientReportOutputSchema } from '@/ai/schemas';


export async function generatePatientReport(input: GeneratePatientReportInput): Promise<GeneratePatientReportOutput> {
  return generatePatientReportFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePatientReportPrompt',
  input: {schema: GeneratePatientReportInputSchema},
  output: {schema: GeneratePatientReportOutputSchema},
  prompt: `You are an expert medical scribe AI specializing in ophthalmology. Your task is to generate a comprehensive, professional, A-to-Z patient report suitable for inclusion in medical records.

Use all the provided information to create a structured report. The output must be plain text, using markdown-style headers (e.g., "**SECTION TITLE**"). Ensure every section is filled with accurate and detailed information derived from the AI analysis. The tone should be formal and clinical.

**Patient Information:**
- Name: {{{patientName}}}
- Age: {{{patientAge}}}
- Gender: {{{patientGender}}}
- Scan Date: {{{scanDate}}}
- Clinical Notes for this scan: {{{clinicalNotes}}}
- Patient's relevant medical history: {{{patientHistory}}}

---
**COMPREHENSIVE AI-POWERED OPHTHALMIC ANALYSIS**
---

**1. DIAGNOSTIC INSIGHTS:**
   - AI Summary: {{{analysis.diagnosticInsights}}}
   - Confidence Score: {{{analysis.confidenceLevel}}}

**2. FINDINGS:**
   - Identified Abnormalities:
{{#each analysis.potentialAbnormalities}}
     - {{{this}}}
{{/each}}
{{#unless analysis.potentialAbnormalities}}
     - None identified.
{{/unless}}
   - Detected Early Signs of Disease:
{{#each analysis.earlySigns}}
     - {{{this}}}
{{/each}}
{{#unless analysis.earlySigns}}
    - None identified.
{{/unless}}
   - Disease Staging: {{{analysis.diseaseStaging}}}

**3. RISK & PROGNOSIS:**
   - Risk Assessment: {{{analysis.riskAssessment}}}
   - Current Risk Level: {{{analysis.riskLevel}}}
   - Differential Diagnosis: {{#each analysis.differentialDiagnosis}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}

**4. PROPOSED TREATMENT & MANAGEMENT:**
   - Suggested Treatments:
{{#each analysis.treatmentSuggestions}}
     - {{{this}}}
{{/each}}
{{#unless analysis.treatmentSuggestions}}
    - None suggested.
{{/unless}}
   - Prevention Suggestions:
{{#each analysis.preventionSuggestions}}
     - {{{this}}}
{{/each}}
{{#unless analysis.preventionSuggestions}}
    - None suggested.
{{/unless}}

**5. FOLLOW-UP & RECOMMENDATIONS:**
   - Follow-Up Plan: {{{analysis.followUpPlan}}}
   - Further Recommendations: {{{analysis.recommendations}}}

---
**DISCLAIMER**
This report was generated by the OptiVision AI assistant. All findings should be reviewed and verified by a qualified medical professional before making any clinical decisions.
---`,
});

const generatePatientReportFlow = ai.defineFlow(
  {
    name: 'generatePatientReportFlow',
    inputSchema: GeneratePatientReportInputSchema,
    outputSchema: GeneratePatientReportOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
