'use client';

import type { Patient, Scan } from '@/lib/types';
import Image from 'next/image';
import { Logo } from './icons';
import { useState, useEffect } from 'react';
import { decrypt } from '@/lib/crypto';


type PrintableReportProps = {
  scan: Scan;
  patient: Patient;
};

const Section = ({ title, children }: { title: string, children: React.ReactNode }) => (
    <section className="mb-6 break-inside-avoid">
      <h2 className="text-sm font-bold text-gray-800 border-b border-gray-300 pb-1 mb-2">{title}</h2>
      <div className="text-xs">{children}</div>
    </section>
);

const InfoPair = ({ label, value }: { label: string, value: React.ReactNode }) => (
    <div>
        <p className="text-gray-500 text-[10px] uppercase tracking-wider">{label}</p>
        <p className="font-semibold">{value || 'N/A'}</p>
    </div>
);


export function PrintableReport({ scan, patient }: PrintableReportProps) {
  const [decryptedData, setDecryptedData] = useState({ history: '', notes: '' });

  useEffect(() => {
    const decryptData = async () => {
      const [history, notes] = await Promise.all([
        decrypt(patient.history),
        decrypt(scan.clinicalNotes || ''),
      ]);
      setDecryptedData({ history, notes });
    };
    decryptData();
  }, [patient.history, scan.clinicalNotes]);
  
  if (!scan.analysis || !scan.report) {
    return null; // Don't render if analysis is missing
  }

  const { analysis } = scan;

  return (
    <div className="bg-white text-gray-900 font-sans p-8 w-[800px]">
      <header className="flex justify-between items-start border-b-2 border-gray-800 pb-4 mb-6">
        <div className="flex items-center gap-3">
          <Logo className="h-10 w-10 text-blue-600" />
          <div>
            <h1 className="text-2xl font-bold text-gray-800">OptiVision AI</h1>
            <p className="text-sm font-medium text-gray-600">Ophthalmic Analysis Report</p>
          </div>
        </div>
        <div className="text-right text-xs">
          <p><strong>Report Date:</strong> {new Date().toLocaleDateString()}</p>
          <p><strong>Scan Date:</strong> {scan.date}</p>
        </div>
      </header>
      
      <Section title="Patient Information">
        <div className="grid grid-cols-4 gap-x-4 gap-y-2">
          <InfoPair label="Full Name" value={patient.name} />
          <InfoPair label="Age" value={patient.age} />
          <InfoPair label="Gender" value={patient.gender} />
          <InfoPair label="Patient ID" value={patient.id} />
          <div className="col-span-4 mt-2">
             <p className="text-gray-500 text-[10px] uppercase tracking-wider">Patient Medical History</p>
             <p className="font-semibold whitespace-pre-wrap">{decryptedData.history || 'N/A'}</p>
          </div>
           <div className="col-span-4 mt-1">
             <p className="text-gray-500 text-[10px] uppercase tracking-wider">Clinical Notes for this Scan</p>
             <p className="font-semibold whitespace-pre-wrap">{decryptedData.notes || 'N/A'}</p>
          </div>
        </div>
      </Section>

      <div className="flex gap-6 items-start">
        <div className="w-[250px] flex-shrink-0">
          <Section title="Scan Image">
              <div className="border rounded-md p-1 bg-gray-50">
                    <Image src={scan.imageUrl} alt={`Scan from ${scan.date}`} width={400} height={300} className="rounded w-full" data-ai-hint="eye scan" />
              </div>
          </Section>
          <Section title="Key Metrics">
             <div className="space-y-2">
                <InfoPair label="Confidence Score" value={`${(analysis.confidenceLevel * 100).toFixed(0)}%`} />
                {analysis.diseaseStaging && <InfoPair label="Disease Staging" value={analysis.diseaseStaging} />}
                <InfoPair label="Risk Level" value={analysis.riskLevel} />
             </div>
          </Section>
        </div>

        <div className="flex-1">
          <Section title="AI Generated Report">
            <div className="prose prose-sm max-w-none text-gray-800 whitespace-pre-wrap">
              {scan.report}
            </div>
          </Section>
        </div>
      </div>

      
      <footer className="pt-4 mt-6 border-t text-center text-[10px] text-gray-500">
        <p>This report was generated by the OptiVision AI assistant. All findings should be reviewed and verified by a qualified medical professional before making any clinical decisions.</p>
        <p>&copy; {new Date().getFullYear()} OptiVision AI. All rights reserved.</p>
      </footer>
    </div>
  );
}
