
type User @table(key: "id") {
  id: String!
  email: String
  displayName: String
}

type Patient @table(key: "id") {
  id: String!
  clinician: User!
  name: String!
  age: Int!
  gender: String!
  lastVisit: Date!
  avatarUrl: String
  riskLevel: String!
  history: String!
  scans: [Scan]! @relation(through: "Scan", from: "patient", to: "scans")
}

type Scan @table(key: "id") {
  id: String!
  patient: Patient!
  clinician: User!
  date: Date!
  imageUrl: String!
  clinicalNotes: String
  status: String!
  analysis: String
  report: String
}
