
# In this file, you can define your database schema using GraphQL.
# For example:
#
# type User @table {
#   id: ID!
#   name: String
#   email: String
# }
#
# For more information, see the Firebase Data Connect documentation:
# https://firebase.google.com/docs/dataconnect

